# This is used to convert the agent name strings used in the search request to the full agent names used in the listings
# agent_dict = {
#     "ami": "Ami Immobilier",
#     "api": "A.P.I.",
#     "arieg": "Arieg'Immo",
#     "arthur": "Arthur Immo",
#     "aude": "Aude Immobilier",
#     "bac": "BAC Immobilier",
#     "beaux": "Beaux Villages",
#     "c21": "Century 21",
#     "cimm": "Cimm Immobilier",
#     "eureka": "Eureka Immobilier",
#     "europe": "Europe Sud Immobilier",
#     "human": "Human Immobilier",
#     "iad": "IAD Immobilier",
#     "l'immo": "L'Immo Chez Toit",
#     "jammes": "Cabinet Jammes",
#     "mm": "M&M Immobilier",
#     "nestenn": "Nestenn",
#     "privee": "Propriétés Privées",
#     "richardson": "Richardson Immobilier",
#     "safti": "Safti",
#     "selection": "Selection Habitat",
#     "sextant": "Sextant",
#     "stephane": "Stéphane Plaza",
#     "time": "Time and Stone Immobilier",
# }
